wip

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -37,36 +37,36 @@ jobs:
           name: test-coverage-report
           path: lesson5/build/reports/jacoco/test/html/index.html
 
-  code-analysis:
-    name: Static Code Analysis
-    runs-on: ubuntu-latest
-    needs: build
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
-        with:
-          java-version: '17'
-          distribution: 'adopt'
-
-      - name: Run SonarCloud analysis
-        working-directory: lesson5
-        env:
-         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-           ./gradlew sonarqube \
-           -Dsonar.projectKey=mastkeey_fj_2024 \
-           -Dsonar.organization=mastkeey \
-           -Dsonar.host.url=https://sonarcloud.io
+#  code-analysis:
+#    name: Static Code Analysis
+#    runs-on: ubuntu-latest
+#    needs: build
+#
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v3
+#
+#      - name: Set up JDK 17
+#        uses: actions/setup-java@v3
+#        with:
+#          java-version: '17'
+#          distribution: 'adopt'
+#
+#      - name: Run SonarCloud analysis
+#        working-directory: lesson5
+#        env:
+#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#        run: |
+#           ./gradlew sonarqube \
+#           -Dsonar.projectKey=mastkeey_fj_2024 \
+#           -Dsonar.organization=mastkeey \
+#           -Dsonar.host.url=https://sonarcloud.io
 
   publish:
     name: Publish Docker Image
     runs-on: ubuntu-latest
-    needs: [build, code-analysis]
+    needs: [ build ]
     if: github.event_name == 'push'
 
     steps:
@@ -75,6 +75,13 @@ jobs:
 
       - name: Log in to GitHub Docker registry
         run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
+
+      - name: Check if JAR file exists
+        run: |
+          if [ ! -f lesson5/build/libs/lesson5.jar ]; then
+            echo "JAR file not found! Check if the build step created the file."
+            exit 1
+          fi
 
       - name: Build Docker image
         run: docker build -t ghcr.io/${{ github.repository }}:latest -f lesson5/Dockerfile .
